name: hesen
description: "A new Flutter project."

publish_to: 'none'

version: 4.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage: ^13.0.2 # Added for receipt uploads
  image_picker: ^1.0.7 # Added for selecting receipts
  http: ^1.2.1
  video_player: ^2.8.6
  chewie: ^1.7.5
  intl: any
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.9.1
  cached_network_image: ^3.3.1
  wakelock_plus: ^1.2.8
  curved_navigation_bar: ^1.0.6
  day_night_switch: ^1.0.4
  uuid: ^4.3.3
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  timezone: ^0.10.1 # Add timezone package
  flutter_dotenv: ^5.1.0 # Add dotenv for environment variables
  crypto: ^3.0.3 # Added for Cloudinary signature generation

  android_pip: ^2.0.1
  provider: ^6.1.2
  flex_color_picker: ^3.7.1
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0 # Added for improved WebView functionality
  html_unescape: ^2.0.0 # Added for HTML entity decoding
  youtube_explode_dart: ^2.5.2
  google_fonts: ^6.2.1
  video_player_win: ^3.2.2
  window_manager: ^0.5.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_android_video: ^1.0.12 # Added for Android video support
  video_thumbnail: ^0.5.3 # Added for extracting video thumbnails on mobile


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#7C52D8"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/sun.png
    - assets/moon.png
    - assets/no-image.png
    - assets/tv.png
    - assets/replay.png
    - assets/maximize.png
    - assets/icon/
    - assets/goal.png
    - assets/table.png


 # Place you logo there
