name: hesen
description: "A new Flutter project."

publish_to: 'none'

version: 4.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.1.1
  http: ^1.2.1
  video_player: ^2.8.6
  chewie: ^1.7.5
  intl: any
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.9.1
  cached_network_image: ^3.3.1
  wakelock_plus: ^1.2.8
  curved_navigation_bar: ^1.0.6
  day_night_switch: ^1.0.4
  uuid: ^4.3.3
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  timezone: ^0.10.1 # Add timezone package
  flutter_dotenv: ^5.1.0 # Add dotenv for environment variables
  unity_ads_plugin: ^0.3.25
  android_pip: ^2.0.1
  provider: ^6.1.2
  flex_color_picker: ^3.7.1
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0 # Added for improved WebView functionality
  html_unescape: ^2.0.0 # Added for HTML entity decoding
  youtube_explode_dart: ^2.5.2
  google_fonts: ^6.2.1


  
dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hex_code" # Optional, if you want a background color
    theme_color: "#hex_code"      # Optional
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  remove_alpha_ios: true # As suggested by the flutter_launcher_icons output

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/sun.png
    - assets/moon.png
    - assets/no-image.png
    - assets/tv.png
    - assets/replay.png
    - assets/maximize.png
    - assets/icon/
    - assets/goal.png
    - assets/table.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700


 # Place you logo there
